ALTER TABLE "tblDocuments" ADD COLUMN IF NOT EXISTS "Leave_From" DATE;
ALTER TABLE "tblDocuments" ADD COLUMN IF NOT EXISTS "Leave_To" DATE;
ALTER TABLE "tblDocuments" ADD COLUMN IF NOT EXISTS "Reason" VARCHAR(255);
ALTER TABLE "tblDocuments" ADD COLUMN IF NOT EXISTS "Notes" TEXT;
ALTER TABLE "tblDocuments" ADD COLUMN IF NOT EXISTS "Status" VARCHAR(50) DEFAULT 'pending';
